name: Shop
version: ${project.version}
main: china.moondrinkwind.minecraft.shop.Shop
api-version: 1.13
authors: [MoonDrinkkWind]
description: a shop plugin
commands:
  shop:
    usage: "
    §b/Shop buy 物品 数量 购买物品\n
    §e/Shop sell 物品 数量 出售物品\n
    §c/Shop add 物品展示名 购买价格 出售价格 添加物品(手持需要出售的物品,需要OP权限)\n
    §a/Shop remove 物品展示名 删除物品(需要OP权限)"